#!/bin/bash

# a program to submit crest jobs to Euler slurm
# @AUTHOR Felix Fleckenstein
#

readonly ARGS="$@"

function usage () {

    echo "usage"
    echo "$0 xyzfile charge unpaired_electrons potential_solvent(can be empty) "

}

function get_args () {
    # Set up default paramters;
     # scratch space in MB (per Node, not per core as in LSF)
    walltime=120 # wall time in h
    output=slurm-%j.out
    mail=True
    solv=""
    charge=0
    unpaired=0
    # Parse the arguments
    local OPTIND OPTARG flag w o m c u
    while getopts ':w:o:m:c:u' flag; do
        case $flag in
            w) walltime=${OPTARG};;
	        o) output=${OPTARG};;
	        m) mail=${OPTARG};; 
            c) charge=${OPTARG};;
            u) unpaired=${OPTARG};;
            *)
              usage
              exit
              ;;
        esac
    done
    xyzfile=${*:$OPTIND:1}

    if [ "$mail" == True  ]; then
	    mail="#SBATCH --mail-type=END,FAIL"
    else
	    mail=""
    fi

}

function main () {

    # make sure you added
    # export MODULEPATH=$MODULEPATH:/cluster/project/chenp/share/modules/modulefiles
    # to your $HOME/.bashrc
    # otherwise it won't find the modules in our group folder

    

    

    local nproc=24
    
    local mem=1000
    local scratchspace=10000
    

    
   
    

    local ifpath=$(readlink -f $xyzfile)
    local ifbase=$(basename $ifpath)
    local ifdir=$(dirname $ifpath)
    local ofpath=${ifpath/.xyz/_out.log}

    sbatch <<---script
#!/bin/bash
#
#SBATCH -J crest_${ifpath}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=$nproc
#SBATCH --mem-per-cpu=$mem
#SBATCH --tmp=$scratchspace
#SBATCH --output=$output
#SBATCH --time=$walltime:00:00
$mail
module purge
module load stack/2024-06 xtb openblas crest/3.0.1
export OMP_NUM_THREAD=24

sacct -j "\$SLURM_JOB_ID" -B

echo "infile: $ifpath"
if [[ -n "$solv" ]] 
then 

	crest $ifpath --gfn2  -chrg $charge -uhf $unpaired -T $nproc --alpb $solv  --scratch \$TMPDIR > $ofpath
else
	crest $ifpath --gfn2  -chrg $charge -uhf $unpaired -T $nproc  --scratch \$TMPDIR > $ofpath
fi
myjobs -j \$SLURM_JOB_ID

--script

}

if [[ -z $ARGS ]]; then
    usage
    exit 1
else
    main $ARGS
fi
