#!/bin/bash


config_file=""

if [[ "$#" -ne 1 ]]; then
    
    echo " No config given, use default"
    

else
    config_file="$1"
fi


current_dir=$(pwd)

echo "$current_dir"


# Default values
job_name="Pipeline"
output_file="slurm-%j.out"
python_output="pipeline_output.log" 


# Submit job to SLURM
sbatch --job-name="$job_name" --output="$output_file" <<EOL
#!/bin/bash
#SBATCH --job-name=$job_name
#SBATCH --output=$output_file
#SBATCH -n 1
#SBATCH --mem-per-cpu=1G
#SBATCH --time=240:00:00


run_pipeline  $config_file > $python_output 2>&1 
EOL
