#!/bin/bash

usage() {
    echo "Usage: $0 config_file"
    exit 1
}
config_file=""

if [[ "$#" -ne 1 ]]; then
    
    echo " No config given, use default"
    usage
    

else
    config_file="$1"
fi


current_dir=$(pwd)

echo "$current_dir"

cp /cluster/home/jlandis/orca_pipeline/src/run_pipeline.py "$current_dir"
cp /cluster/home/jlandis/orca_pipeline/src/hpc_driver.py "$current_dir"
cp /cluster/home/jlandis/orca_pipeline/src/step_runner.py "$current_dir"
cp /cluster/home/jlandis/orca_pipeline/src/pipeline_manager.py "$current_dir"
cp /cluster/home/jlandis/orca_pipeline/src/constants.py "$current_dir" 
cp /cluster/home/jlandis/orca_pipeline/src/chemistry.py "$current_dir"

# Default values
job_name="Pipeline"
output_file="slurm-%j.out"
file="run_pipeline.py"



# Submit job to SLURM
sbatch --job-name="$job_name" --output="$output_file" <<EOL
#!/bin/bash
#SBATCH --job-name=$job_name
#SBATCH --output=$output_file
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=24:00:00

module load orca
python3 $file  $config_file
EOL