#!/bin/bash 
echo "Usage: ssubpipeline -n job_name -o output_file -e error_file -f file -c charge -m mult -I images"

current_dir=$(pwd)

echo $current_dir

# Default values
job_name="Pipeline"
output_file="slurm-%j.out"
error_file="slurm-%j.err"
file="run.py"
charge=0
mult=1
images=8    

# Parse input options
while getopts ":n:o:e:f:c:m:I:" opt; do
    case $opt in
        n) job_name="$OPTARG"
        ;;
        o) output_file="$OPTARG"
        ;;
        e) error_file="$OPTARG"
        ;;
        f) file="$OPTARG"
        ;;
        c) charge="$OPTARG"
        ;;
        m) mult="$OPTARG"
        ;;
        I) images="$OPTARG"
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
                exit 1
        ;;
    esac
done

# Submit the SLURM job
sbatch --job-name="$job_name" --output="$output_file" --error="$error_file" --time=120:00:00 --ntasks=1 --mem-per-cpu=1G <<EOF
#!/bin/bash

cd $current_dir

python3 $file $charge $mult > run.out 2> run.err
EOF